# @author: Helvecio Neto <helveciofneto@gmail.com>
Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.vm.hostname = "linuxserver01"
  config.vm.network "private_network", ip: "192.168.56.21"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "256"
  end
  #Copy SSH key and inventory files to VM.
  #Ref https://www.vagrantup.com/docs/provisioning/file.html
  config.vm.provision "file", source: "../../ansible/ssh_keys/ansible_ssh_key.pub", destination: "$HOME/.ssh/ansible_ssh_key.pub"

  config.vm.provision "shell", inline: <<-SHELL

    su - vagrant -c 'cat "$HOME/.ssh/ansible_ssh_key.pub" >> $HOME/.ssh/authorized_keys'

  SHELL
end
